# **IMPORT LIBRARY**

Tahap ini dilakukan untuk mengimpor berbagai library yang akan diperlukan untuk mendukung proses pengolahan serta analisis data.

In [35]:
import numpy as np
import os
import pandas as pd
import random

# **LOAD DATA**

Tahap ini dilakukan untuk memuat *(load)* dataset yang akan digunakan dalam proses analisis.

In [36]:
df = pd.read_csv(
    "../data/raw/transactions/data_transactions.csv",
    sep=";"
)

In [37]:
# Cek isi data dalam 5 baris awal
df.head()

,Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Revenue,Store_Location,Payment_Method,Province,Unit Cost,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,JATNG_PURJO_00001,01/01/2023,Nabati Wafer,Snacks,7,5.0,35.000,Purworejo,Card,Jawa Tengah,4.400,NaN,NaN,NaN,NaN,NaN
1,JABAR_SUMNG_00002,01/01/2023,Sedaap Soto,Instant Noodles,16,3.8,60.800,Sumedang,Cash,Jawa Barat,3.420,NaN,NaN,NaN,NaN,NaN
2,JABAR_BANAT_00003,01/01/2023,Sari Roti Tawar,Snacks,2,12.0,24.000,Bandung Barat,Cash,Jawa Barat,10.560,NaN,NaN,NaN,NaN,NaN
3,JABAR_SUMNG_00004,01/01/2023,Pantene Shampoo 1L,Personal Care,6,45.0,270.000,Sumedang,Cash,Jawa Barat,33.750,NaN,NaN,NaN,NaN,NaN
4,JATIM_MADUN_00005,01/01/2023,Tolako Minuman Herbal,Health,16,8.5,136.000,Madiun,Cash,Jawa Timur,6.375,NaN,NaN,NaN,NaN,NaN

In [38]:
df.shape

(200000, 16)

**Insight:**

- Dataset berhasil dimuat ke lingkungan kerja dan terbaca dalam bentuk *dataframe*, sehingga siap digunakan pada proses analisis selanjutnya.
- Pemeriksaan awal menggunakan `df.head()` menunjukkan bahwa data berhasil ditampilkan dan setiap kolom dapat terbaca dengan baik.
- Berdasarkan df.shape, dataset terdiri dari 200.000 baris dan 16 kolom, sehingga memiliki jumlah data yang memadai untuk dilakukan proses eksplorasi, pembersihan, dan analisis lebih lanjut.

# **CHECK DATA**

Pada tahap ini dilakukan pemeriksaan awal terhadap dataset untuk memahami karakteristik data. Pemeriksaan mencakup tipe data tiap variabel, identifikasi missing value, pengecekan data bernilai 0 pada kolom tertentu, serta analisis nilai unik pada variabel `Product_Name`, `Category`, dan `Province`.

In [39]:
# Cek type data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Transaction_ID  200000 non-null  str
 1   Date            200000 non-null  str
 2   Product_Name    200000 non-null  str
 3   Category        200000 non-null  str
 4   Units_Sold      200000 non-null  int64
 5   Unit_Price      200000 non-null  float64
 6   Revenue         200000 non-null  str
 7   Store_Location  200000 non-null  str
 8   Payment_Method  200000 non-null  str
 9   Province        200000 non-null  str
 10  Unit Cost       200000 non-null  float64
 11  Unnamed: 11     0 non-null       float64
 12  Unnamed: 12     0 non-null       float64
 13  Unnamed: 13     0 non-null       float64
 14  Unnamed: 14     0 non-null       float64
 15  Unnamed: 15     0 non-null       float64
dtypes: float64(7), int64(1), str(8)
memory usage: 40.5 MB

In [40]:
# Cek missing value
df.isna().sum()

Transaction_ID         0
Date                   0
Product_Name           0
Category               0
Units_Sold             0
Unit_Price             0
Revenue                0
Store_Location         0
Payment_Method         0
Province               0
Unit Cost              0
Unnamed: 11       200000
Unnamed: 12       200000
Unnamed: 13       200000
Unnamed: 14       200000
Unnamed: 15       200000
dtype: int64

In [41]:
# Cek nilai 0 di kolom Units_Sold, Unit_Price, dan Revenue
df_zero = df[
    (df['Units_Sold'] == 0) |
    (df['Unit_Price'] == 0.0) |
    (df['Revenue'].isna())
]

df_zero

Empty DataFrame
Columns: [Transaction_ID, Date, Product_Name, Category, Units_Sold, Unit_Price, Revenue, Store_Location, Payment_Method, Province, Unit Cost, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15]
Index: []

In [42]:
# Cek isi kolom Product_Name
sorted(df['Product_Name'].unique())

['ABC Kecap Manis 620ml',
 'Aqua 600ml',
 'Beras Maknyuss 5kg',
 'Bimoli Minyak Goreng 2L',
 'Frisian Flag Susu Kental Manis',
 'Indomie Goreng',
 'Indomilk UHT 1L',
 'Lifebuoy Body Wash',
 'Milo 1kg',
 'Nabati Wafer',
 'Pantene Shampoo 1L',
 'Pepsodent Toothpaste',
 'Pocari Sweat 500ml',
 'Rexona Deodorant',
 'Sampoerna Mild 16',
 'Sari Roti Tawar',
 'Sedaap Soto',
 'SilverQueen Milk Chocolate',
 'Tolak Angin',
 'Tolako Minuman Herbal']

In [43]:
# Cek isi kolom Category
sorted(df['Category'].unique())

['Drinks',
 'Groceries',
 'Health',
 'Instant Noodles',
 'Personal Care',
 'Smokes',
 'Snacks']

In [44]:
# Cek isi kolom Province
sorted(df['Province'].unique())

['Banten',
 'DI Yogyakarta',
 'DKI Jakarta',
 'Jawa Barat',
 'Jawa Tengah',
 'Jawa Timur']

**Insight:**

- Hasil menunjukkan tidak terdapat *missing value* pada kolom utama, seperti `Transaction_ID`, `Date`, `Product_Name`, `Category`, `Units_Sold`, `Unit_Price`, `Revenue`, dan `Province`. Akan tetapi, ditemukan kolom `Unnamed: 11` hingga `Unnamed: 15` yang seluruh nilainya kosong sehingga dapat dihapus pada tahap pembersihan data karena tidak memberikan informasi.
- Beberapa variabel masih memerlukan perubahan tipe data agar sesuai dengan kebutuhan analisis. Kolom `Date` perlu dikonversi ke format *datetime*, `Category` lebih tepat direpresentasikan sebagai tipe `category` karena berisi kelompok data kategorikal dengan jumlah nilai unik yang terbatas, dan `Revenue` perlu diubah menjadi tipe numerik.
- Variabel `Product_Name` memiliki 20 produk unik, `Category` terdiri dari 7 kategori produk, dan `Province` mencakup 6 wilayah provinsi.
- Hasil pemeriksaan awal menunjukkan bahwa dataset memerlukan proses cleaning untuk meningkatkan kualitas data sebelum dilakukan analisis lanjutan.

# **DATA CLEANING**

Pada tahap ini dilakukan proses pembersihan data untuk meningkatkan kualitas dan konsistensi dataset sebelum analisis. Proses meliputi penghapusan kolom yang tidak diperlukan, penyesuaian tipe data, standarisasi data pada beberapa variabel, serta agregasi data penjualan harian untuk menghasilkan struktur data yang lebih siap untuk dianalisis.

In [45]:
# Hapus kolom tidak terpakai
df = df.drop(columns=[col for col in df.columns if 'Unnamed' in col])
df = df.drop(columns=['Payment_Method', 'Store_Location', 'Unit Cost', 'Transaction_ID'])

In [46]:
# Ubah Unit_Price menjadi rupiah
df['Unit_Price'] = df['Unit_Price'] * 1000

In [47]:
# Ubah type data
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')
df['Revenue'] = df['Revenue'].str.replace('.', '', regex=False).astype(float)
df['Category'] = df['Category'].astype('category')

# Cek type data kembali
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          200000 non-null  datetime64[us]
 1   Product_Name  200000 non-null  str
 2   Category      200000 non-null  category
 3   Units_Sold    200000 non-null  int64
 4   Unit_Price    200000 non-null  float64
 5   Revenue       200000 non-null  float64
 6   Province      200000 non-null  str
dtypes: category(1), datetime64[us](1), float64(2), int64(1), str(2)
memory usage: 14.6 MB

In [48]:
# Ganti Tolako Minuman Herbal menjadi Tolak Linu
df['Product_Name'] = df['Product_Name'].replace({
    'Tolako Minuman Herbal': 'Tolak Linu',
    'Indomilk UHT 1L': 'Indomilk UHT Full Cream 1L'
})

In [49]:
# Ganti kategori Sari Roti Tawar menjadi Bakery
df['Category'] = df['Category'].cat.add_categories('Bakery')

df.loc[
    df['Product_Name'].str.contains('Sari Roti Tawar', case=False),
    'Category'
] = 'Bakery'

In [50]:
# Agregasi penjualan harian
df_grouped = df.groupby(
    ['Date', 'Province', 'Product_Name'],
    as_index=False
).agg({
    'Units_Sold': 'sum',
    'Revenue': 'sum',
    'Unit_Price': 'mean',
    'Category': 'first',
})

# Reset index
df_grouped = df_grouped.reset_index(drop=True)

# Reorder kolom
df = df_grouped[[
    'Date',
    'Product_Name',
    'Category',
    'Units_Sold',
    'Unit_Price',
    'Revenue',
    'Province',
]]

In [51]:
# Cek isi data dalam 5 baris awal
df.head()

,Date,Product_Name,Category,Units_Sold,Unit_Price,Revenue,Province
0,2023-01-01,ABC Kecap Manis 620ml,Groceries,13,18000.0,234000.0,Banten
1,2023-01-01,Aqua 600ml,Drinks,7,4000.0,28000.0,Banten
2,2023-01-01,Bimoli Minyak Goreng 2L,Groceries,4,33000.0,132000.0,Banten
3,2023-01-01,Frisian Flag Susu Kental Manis,Groceries,20,10000.0,200000.0,Banten
4,2023-01-01,Indomie Goreng,Instant Noodles,7,4200.0,29400.0,Banten

**Insight:**

- Kolom yang tidak relevan dan kolom kosong berhasil dihapus sehingga dataset menyisakan variabel yang mendukung analisis.
- Tipe data pada beberapa variabel sudah disesuaikan, yaitu `Date` menjadi format *datetime*, `Revenue` menjadi numerik, serta `Category` menjadi tipe `category`.
- Dilakukan juga standarisasi pada nama produk dan kategori untuk mengurangi inkonsistensi data, yang meliputi penyesuaian nama produk serta penambahan kategori `Bakery`.
- Data transaksi berhasil diagregasi menjadi penjualan harian berdasarkan tanggal, provinsi, dan produk sehingga menghasilkan struktur data yang lebih terorganisasi.
- Proses ini menghasilkan dataset yang lebih bersih, konsisten, dan siap digunakan pada tahap berikutnya.

# **NEW PRODUCT**

Pada tahap ini dilakukan transformasi data untuk penambahan jenis produk dalam dataset berdasarkan `Province`. Proses ini meliputi penggantian produk awal menjadi produk baru, penyesuaian kategori yang sesuai dengan produk, pengurutan kembali data, serta pembentukan ulang `Transaction_ID` untuk analisis lebih lanjut.

In [52]:
# List produk lama
old_products = [
    'ABC Kecap Manis 620ml', 'Aqua 600ml', 'Beras Maknyuss 5kg', 'Bimoli Minyak Goreng 2L',
    'Frisian Flag Susu Kental Manis', 'Indomie Goreng', 'Indomilk UHT Full Cream 1L',
    'Lifebuoy Body Wash', 'Milo 1kg', 'Nabati Wafer', 'Pantene Shampoo 1L', 'Pepsodent Toothpaste',
    'Pocari Sweat 500ml', 'Rexona Deodorant', 'Sampoerna Mild 16', 'Sari Roti Tawar',
    'Sedaap Soto', 'SilverQueen Milk Chocolate', 'Tolak Angin', 'Tolak Linu'
]

In [53]:
# List produk baru
new_products = [
    ['ABC Kecap Manis 620ml', 'Sedaap Kecap Manis 550ml', 'Bango Kecap Manis 189gr',
     'ABC Kecap Asin 620ml', 'Indofood Saus Tomat 335ml', 'Saori Saus Tiram 270ml'],

    ['Aqua 600ml', 'Le Minerale 600ml', 'Teh Pucuk Harum 350ml',
     'ABC Sari Kacang Hijau 250ml', 'Teh Kotak 200ml', 'Floridina 350ml'],

    ['Beras Maknyuss 5kg', 'Beras Rojolele 5kg', 'Beras Sania 5kg',
     'Beras Ramos Super 5kg',  'Gula Pasir 3kg', 'SGM Soya Vanila 400gr'],

    ['Bimoli Minyak Goreng 2L', 'Hadalabo Face Wash 50gr', 'Telor Ayam 1kg',
     'Nabati Kaleng 287gr', 'Stella Spray 400ml', 'Evangeline Parfume 100ml'],

    ['Frisian Flag Susu Kental Manis', 'Roma Sari Gandum 149gr', 'Roma Kelapa 300gr',
     'Hatari Malkist 260gr', 'Oreo Sandwich Roll 119gr', 'Kanzler Singles Sosis'],

    ['Indomie Goreng', 'Indomie Rendang', 'Indomie Soto',
     'Gaga 100 Jalapeno', 'Gaga 100 Lada Hitam', 'Gaga 100 Habanero'],

    ['Indomilk UHT Full Cream 1L', 'Indomilk UHT Cokelat 1L', 'Fanta 1L',
     'Coca Cola 1L',  'Sprite 1L', 'Buavita 250ml'],

    ['Lifebuoy Body Wash', 'Dettol Body Wash 200ml',  'Sleek Detergen Cair 450ml',
     'So Klin Liquid 720ml', 'Downy Pewangi 550ml', 'Wipol 750ml'],

    ['Milo 1kg', 'Prenagen 360gr', 'Sweety Silver Pants',
     'Monde Butter Cookies', 'Wardah Cushion', 'Make Over Lipmatte'],

    ['Nabati Wafer', 'Wafello Wafer', 'Garam Dapur',
     'Masako', 'Sasa Micin', 'Taro 32gr'],

    ['Pantene Shampoo 1L', 'Pantene Conditioner 150ml', 'Quacker Oatmeal Instan 800gr',
     'Glad2glow Moisturizer', 'Koko Crunch', 'Tropicana Slim'],

    ['Pepsodent Toothpaste', 'Kobe Tepung Roti 200gr', 'ForVita Margarin 250gr',
     'Segitiga Biru Tepung Terigu 1kg', 'Prochiz Slices Keju Cheddar', 'Formula Sikat Gigi'],

    ['Pocari Sweat 500ml', 'Cotton Bud', 'Mama Lemon Sabun Cuci Piring',
     'Pop Mie 75gr', 'Tejahe Permen', 'Poci Teh Celup'],

    ['Rexona Deodorant', 'Hanasui Masker Wajah', 'Acnes Obat Jerawat',
     'Implora Moisturizer', 'Betadine Obat Luka 5gr', 'OMG Lipcream'],

    ['Sampoerna Mild 16', 'Hs Rokok Filter', 'Clas Mild',
     'LA Ice', 'Marlboro Gold', 'Esse Change'],

    ['Sari Roti Tawar', 'Sari Roti Sobek 72gr', 'Sari Roti Klasik Kasur 185gr',
     'Sari Roti Sisir 165gr', 'Sari Kue Lapis Surabaya', 'Sari Kue Cheesecake'],

    ['Sedaap Soto', 'Sedaap Goreng', 'Sedaap Singapore Laksa',
     'Sedaap Selection', 'Sedaap Kari Spesial', 'Sedaap Ayam Bawang'],

    ['SilverQueen Milk Chocolate', 'Dua Kelinci Kacang', 'Top Coffee Sachet Pack',
     'Neo Coffee Sachet Pack', 'Nescafe KitKat 220ml', 'Gajah Kopi Tubruk'],

    ['Tolak Angin', 'Antimo Obat Anti Mabuk', 'Baygon Obat Nyamuk Bakar',
     'Kiranti Pegel Linu', 'Konidin OBH', 'Enervon C Vitamin'],

    ['Tolak Linu', 'Diapet', 'Hit Magic Obat Nyamuk Bakar',
     'Kool Fever', 'You C1000 140ml', 'Kaki Tiga Larutan 500ml']
]

In [54]:
# List Province
provinces = [
    'Banten',
    'DI Yogyakarta',
    'DKI Jakarta',
    'Jawa Barat',
    'Jawa Tengah',
    'Jawa Timur'
]

In [55]:
# Membuat product_mapping untuk produk lama dan baru
product_mapping = dict(zip(old_products, new_products))

# Fungsi untuk mengganti nama produk berdasarkan provinsi
def replace_product(row):

    province = row['Province']
    old_product = row['Product_Name']
    province_idx = provinces.index(province)
    if old_product in product_mapping:
        return product_mapping[old_product][province_idx]
    return old_product

# Replace Product_Name dengan produk baru
df['Product_Name'] = df.apply(replace_product, axis=1)

In [56]:
# List Category baru untuk produk baru
new_category = {
    "Drinks": [
        "Frisian Flag Susu Kental Manis",
        "Top Coffee Sachet Pack",
        "Neo Coffee Sachet Pack",
        "Nescafe KitKat 220ml",
        "SGM Soya Vanila 400gr",
        "Gajah Kopi Tubruk",
    ],

    "Personal Care": [
        "Hadalabo Face Wash 50gr",
        "Cotton Bud",
        "Sweety Silver Pants",
        "Evangeline Parfume 100ml",
        "Formula Sikat Gigi"
    ],

    "Snacks": [
        "Roma Sari Gandum 149gr",
        "Roma Kelapa 300gr",
        "Quacker Oatmeal Instan 800gr",
        "Hatari Malkist 260gr",
        "Koko Crunch",
        "Nabati Kaleng 287gr",
        "Oreo Sandwich Roll 119gr",
        "Monde Butter Cookies",
        "Tejahe Permen",
        "Kanzler Singles Sosis"
    ],

    "Groceries": [
        "Garam Dapur",
        "Kobe Tepung Roti 200gr",
        "Masako",
        "ForVita Margarin 250gr",
        "Segitiga Biru Tepung Terigu 1kg",
        "Sasa Micin",
        "Tropicana Slim",
        "Prochiz Slices Keju Cheddar",
    ],

    "Home": [
        "Mama Lemon Sabun Cuci Piring",
        "Hit Magic Obat Nyamuk Bakar",
        "Sleek Detergen Cair 450ml",
        "Baygon Obat Nyamuk Bakar",
        "So Klin Liquid 720ml",
        "Stella Spray 400ml",
        "Downy Pewangi 550ml",
        "Wipol 750ml"
    ],

    "Health": [
        "Antimo Obat Anti Mabuk",
        "Betadine Obat Luka 5gr"
    ],

    "Make Up": [
        "Wardah Cushion",
        "Make Over Lipmatte",
        "OMG Lipcream"
    ],

    "Instant Noodles": [
        "Pop Mie 75gr"
    ]
}

# Membuat mapping product untuk Category
category_mapping = {}
for category, products in new_category.items():
    for product in products:
        category_mapping[product] = category

# Replace Category baru
df['Category'] = df['Product_Name'].map(category_mapping).fillna(df['Category'])

In [57]:
# Mengurutkan dataset berdasarkan tanggal dan nama produk
df = df.sort_values(by=["Date", "Product_Name"]).reset_index(drop=True)

# Membuat kolom Transaction ID
df.insert(
    0,
    "Transaction_ID",
    [f"TRX{i:06d}" for i in range(1, len(df)+1)]
)

# Hapus kolom Province
df = df.drop(columns=['Province'])

In [58]:
# Cek isi data kembali
df.head()

,Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Revenue
0,TRX000001,2023-01-01,ABC Kecap Asin 620ml,Groceries,47,18000.0,846000.0
1,TRX000002,2023-01-01,ABC Kecap Manis 620ml,Groceries,13,18000.0,234000.0
2,TRX000003,2023-01-01,ABC Sari Kacang Hijau 250ml,Drinks,2,4000.0,8000.0
3,TRX000004,2023-01-01,Aqua 600ml,Drinks,7,4000.0,28000.0
4,TRX000005,2023-01-01,Bango Kecap Manis 189gr,Groceries,19,18000.0,342000.0

In [60]:
# Save ke CSV
os.makedirs("../data/processed/transactions", exist_ok=True)
df.to_csv("../data/processed/transactions/transactions_raw.csv", index=False)

**Insight:**

- Dataset berhasil diperluas dengan variasi produk baru yang berbeda pada setiap provinsi, sehingga menghasilkan data yang lebih beragam.
- Kategori produk telah disesuaikan agar tetap relevan dengan karakteristik produk baru, termasuk penambahan beberapa kategori baru agar pengelompokkan data tetap konsisten.
- Dataset disusun kembali melalui pengurutan data serta pembentukan ulang `Transaction_ID` untuk mempertahankan identitas unik setiap transaksi.
- Kolom yang tidak lagi diperlukan pada dataset akhir telah dihapus sehingga data siap digunakan pada tahap analisis berikutnya.

# **DATA STOCK**

Tahap ini dilakukan untuk membentuk dataset stok berdasarkan data transaksi penjualan untuk menggambarkan pergerakan persediaan produk. Proses ini mencakup pembentukan variabel `Stock_In`, `Stock_Out`, dan `Stok_End`. Pengurutan data berdasarkan tanggal dan produk, serta simulasi penambahan stok secara terjadwal maupun darurat agar ketersediaan stok tetap terjaga selama periode penjualan.

In [61]:
# Load dataset buntuk data stock
df_transactions = df

In [62]:
# Membuat kolom baru untuk stock
df_transactions["Stock_Out"] = df_transactions["Units_Sold"]
df_transactions["Stock_In"] = 0
df_transactions["Stock_End"] = 0

In [63]:
# Urutkan data berdasarkan Product_Name dan Date
df_transactions = df_transactions.sort_values(
    by=["Product_Name", "Date"]
).reset_index(drop=True)

In [64]:
# Membuat hasil random selalu sama setiap run
random.seed(42)

# Simpan stock terakhir produk
stock_product = {}

# Hari restock toko
restock_day = ["Monday", "Thursday"]

for i in range(len(df)):
    product = df_transactions.loc[i, "Product_Name"]
    date = df.loc[i, "Date"]

    # Stok awal produk
    if product not in stock_product:
        additional_stock = random.randint(300, 700)
        df_transactions.loc[i, "Stock_In"] = additional_stock
        stock = additional_stock
    else:
        stock = stock_product[product]

    # Jumlah stock out
    stock_out = df_transactions.loc[i, "Stock_Out"]

    # Restock terjadwal
    if date.day_name() in restock_day:
        if stock < 200:
            additional_stock = random.randint(250, 600)
            df_transactions.loc[i, "Stock_In"] += additional_stock
            stock += additional_stock

    # Restock darurat
    if stock < stock_out:
        additional_stock = random.randint(300, 700)
        df_transactions.loc[i, "Stock_In"] += additional_stock
        stock += additional_stock

    # Stock berkurang karena penjualan
    stock -= stock_out

    # Batas stock
    stock = min(stock, 1000)
    stock = max(stock, 0)

    # Simpan stock end
    df_transactions.loc[i, "Stock_End"] = stock
    stock_product[product] = stock

In [65]:
# Dataset akhir
df_stock = df_transactions[[
    "Date",
    "Product_Name",
    "Stock_In",
    "Stock_Out",
    "Stock_End"
]].copy()

# Urutkan berdasarkan Date dan Product_Name
df_stock = df_stock.sort_values(
    by=["Date", "Product_Name"]
).reset_index(drop=True)

# Cek isi dataset
df_stock.head()

        Date                 Product_Name  Stock_In  Stock_Out  Stock_End
0 2023-01-01         ABC Kecap Asin 620ml       627         47        580
1 2023-01-01        ABC Kecap Manis 620ml       486         13        473
2 2023-01-01  ABC Sari Kacang Hijau 250ml       673          2        671
3 2023-01-01                   Aqua 600ml       690          7        683
4 2023-01-01      Bango Kecap Manis 189gr       674         19        655

In [66]:
# Save ke CSV
df_stock.to_csv("../data/processed/transactions/stock_raw.csv", index=False)

**Insight:**

- Dataset stok berhasil dibentuk dengan penambahan informasi `Stock_In`, `Stock_Out`, dan `Stock_End` untuk menggambarkan pergerakan persediaan pada setiap produk.
- Penerapan simulasi restock terjadwal dan restock darurat memungkinkan stok tetap tersedia ketika jumlah persediaan menurun atau tidak mencukupi jumlah penjualan.
- Pengurutan data berdasarkan produk dan tanggal membantu menjaga konsistensi perhitungan stok dari waktu ke waktu.
- Dataset menghasilkan informasi persediaan yang lebih terstruktur sehingga dapat digunakan untuk analisis stok.

# **MERGE DATASET TRANSACTIONS DAN STOCK**

Tahap ini dilakukan untuk menggabungkan dataset transaksi dan dataset stok untuk menghasilkan data yang lebih lengkap. Proses ini mencakup penghapusan kolom yang tidak diperlukan pada dataset transaksi, penggabungan data berdasarkan `Date` dan `Product_Name`, serta pengurutan ulang dataset untuk menjagka konsistensi data pada proses analisis selanjutnya.

In [67]:
# Hapus kolom yang tidak dipakai pada dataset transaction
df_transactions = df_transactions.drop(
    columns=[
        "Stock_In",
        "Stock_Out",
        "Stock_End"
    ]
)

In [68]:
# Gabung kedua dataset
df_merge = pd.merge(
    df_transactions,
    df_stock,
    on=["Date", "Product_Name"],
    how="left"
)

# Urutkan berdasarkan Date dan Product_Name
df_merge = df_merge.sort_values(
    by=["Date", "Product_Name"]
).reset_index(drop=True)

# Cek isi dataset
df_merge.head()

,Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Revenue,Stock_In,Stock_Out,Stock_End
0,TRX000001,2023-01-01,ABC Kecap Asin 620ml,Groceries,47,18000.0,846000.0,627,47,580
1,TRX000002,2023-01-01,ABC Kecap Manis 620ml,Groceries,13,18000.0,234000.0,486,13,473
2,TRX000003,2023-01-01,ABC Sari Kacang Hijau 250ml,Drinks,2,4000.0,8000.0,673,2,671
3,TRX000004,2023-01-01,Aqua 600ml,Drinks,7,4000.0,28000.0,690,7,683
4,TRX000005,2023-01-01,Bango Kecap Manis 189gr,Groceries,19,18000.0,342000.0,674,19,655

In [69]:
# Save ke CSV
df_merge.to_csv("../data/processed/transactions/transactions_clean.csv", index=False)

**Insight:**

- Dataset transaksi dan stok berhasil digabungkan sehingga menghasilkan dataset yang lebih lengkap.
- Penggabungan data berdasarkan `Date` dan `Product_Name` memungkinkan informasi transaksi dan pergerakan stok saling terhubung secara konsisten.
- Pengurutan ulang data berdasarkan tanggal dan nama produk menghasilkan dataset yang lebih rapi dan mudah digunakan pada proses analisis selanjutnya.
- Dataset akhir telah memuat informasi transaksi sekaligus stok sehingga lebih siap digunakan untuk eksplorasi data maupun analisis lanjutan.